#Requires -Version 5.1
# Refreshes the pinned contract snapshot in contract/ from a kit checkout.
# Usage: powershell -NoProfile -ExecutionPolicy Bypass -File tools\Update-ContractSnapshot.ps1 -KitRoot D:\cabinet\frieds-retrogaming-kit
[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string] $KitRoot,
    [string] $Branch = 'origin/main'
)
$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
$tmp = Join-Path ([IO.Path]::GetTempPath()) ('kit-contract-' + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force -Path $tmp | Out-Null
# Git writes UTF-8; PowerShell 5.1 decodes console output with [Console]::OutputEncoding, which is not UTF-8 by
# default. Every blob read below goes through the console, so the encoding is fixed for the whole run.
$savedEncoding = [Console]::OutputEncoding
try {
    [Console]::OutputEncoding = New-Object System.Text.UTF8Encoding($false)
    $commit = (git -C $KitRoot rev-parse $Branch).Trim()
    $apiBlob = (git -C $KitRoot cat-file blob "${Branch}:API.md") -join "`n"
    $version = (git -C $KitRoot show "${Branch}:VERSION") -join "`n"
    if (-not $apiBlob) { throw "no API.md in ${Branch}" }
    $apiFile = Join-Path $tmp 'API.md'
    [IO.File]::WriteAllText($apiFile, $apiBlob + "`n", (New-Object System.Text.UTF8Encoding($false)))
    $sha = (Get-FileHash -Algorithm SHA256 -Path $apiFile).Hash.ToLower()
    $apiVersion = if ($apiBlob -match '(?m)^\| `ApiVersion` \| string \| `([0-9.]+)`') { $Matches[1] } else { 'unknown' }

    $header = @(
        '<!--'
        '  PINNED CONTRACT SNAPSHOT - DO NOT EDIT THIS FILE.'
        ''
        "  Source:      https://github.com/kburna243/frieds-retrogaming-kit  (VERSION $version)"
        "  Kit branch:  $Branch"
        "  Kit commit:  $commit"
        "  Fetched:     $(Get-Date -Format 'yyyy-MM-dd')"
        "  SHA-256:     $sha"
        "  ApiVersion:  $apiVersion"
        ''
        '  The kit owns this contract. This snapshot is what the harness is developed and tested against when no'
        '  kit checkout is at hand. See contract/README.md for how to refresh it and what happens on drift.'
        '-->'
        ''
    ) -join "`n"
    New-Item -ItemType Directory -Force -Path (Join-Path $repo 'contract') | Out-Null
    [IO.File]::WriteAllText((Join-Path $repo 'contract/API.md'), $header + $apiBlob + "`n", (New-Object System.Text.UTF8Encoding($false)))

    # Catalog snapshot: asked from the kit itself, at exactly the pinned commit. A detached worktree of $commit is
    # created next to the checkout, its own api\Invoke-KitApi.ps1 answers "operations", and the worktree is removed
    # again. Nothing is re-implemented here (an earlier version listed the fixed operations by hand and missed
    # backup.remove and the profile.* parameters of kit 0.3.0), and an uncommitted checkout cannot leak in.
    $worktree = Join-Path $tmp 'kit'
    git -C $KitRoot worktree add --detach --quiet $worktree $commit
    if ($LASTEXITCODE -ne 0) { throw "git worktree add failed ($LASTEXITCODE)" }
    try {
        $powerShell = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
        $live = & $powerShell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $worktree 'api\Invoke-KitApi.ps1') -Operation operations
        if ($LASTEXITCODE -ne 0) { throw "the kit at $commit refused the catalog call (exit $LASTEXITCODE)" }
    } finally {
        git -C $KitRoot worktree remove --force $worktree
    }
    $raw = Join-Path $tmp 'operations.json'
    [IO.File]::WriteAllText($raw, ($live -join "`n"), (New-Object System.Text.UTF8Encoding($false)))
    & node (Join-Path $PSScriptRoot 'write-catalog-snapshot.mjs') $raw (Join-Path $repo 'contract/catalog-v1.json') $apiVersion $commit $version $Branch (Get-Date -Format 'yyyy-MM-dd')
    if ($LASTEXITCODE -ne 0) { throw "write-catalog-snapshot.mjs failed ($LASTEXITCODE)" }
    "API.md   sha256 $sha"
    "commit   $commit"
} finally {
    [Console]::OutputEncoding = $savedEncoding
    Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
}
